### ISSUE TITLE
Creating a new meaning between two words

### ISSUE THREAD

**Issue by blegat** [blegat/openvoc#11]
When creating a new meaning between two words, at the line `newmeaning = Meaning.create!`, I get

    Pro can't be blank, Contra can't be blank, Confidence can't be blank

**Comment by pverbist95** [comment]
Indeed, I added 3 mandatory fields to Meanings: Pro, Contra and Confidence.
These values can be used to evaluate the confidence of a meaning.
Pro is the number of "positives votes for the meaning"
Contra is the number of "negatives votes for the meaning"
Confidence is the ratio Pro/(Pro + Contra)

Basically (it was just a idea) all new meanings start with [Pro = 1, Contra = 9, Confidence = 0.1]. So, when someone add a new meaning, we only trust it at 10%. 

One way (not yet implemented) to use these 3 new fields could be: 
-When somebody believes the meaning is correct, the "Pro" value is updated +1
-When somebody believes the meaning is incorrect, the "Contra" value is updated +1
Of course, instead of updating by a +1 step, we could update by +2, +3, or more, depending on the "confidence" we have in the user.
@blegat: What do you think about it?

Consider again the example with the all new meaning [Pro = 1, Contra = 9, Confidence = 0.1]
If 8 people mark it as correct, the meaning will have as characteristics [Pro = (1+8 =) 9, Contra = (9+0 =) 9, Confidence = 0.5]. The confidence will be 0.5 = 50%
If 90 people mark it as correct, the meaning will have as characteristics [Pro = 1+90 = 91, Contra = 9+0 = 9, Confidence = 0.9]. The confidence will be 0.91 = 91%
If 50 people mark it as correct and 10 people mark it as incorrect, the meaning will have as characteristics [Pro = 1+50 = 51, Contra = 9+10 = 19, Confidence = 0.9]. The confidence will be 0.72 = 72%

In your case, using `newmeaning = Meaning.create!(pro:1, contra: 9, confidence:0.1)` should solve the problem :)

I will make the values [Pro = 1, Contra = 9, Confidence = 0.1] by default in the model in a future commit.

**Comment by blegat** [comment]
Pourquoi garder un champ Confidence dans la db alors qu'il se calcule directement en connaissant les deux autres ?
Une question important est:
Garde-t-on la liste de tous les gens qui ont voté ? Sinon comment on sait si un mec a déjà voté pour l'empêcher de revoter ?
Seulement, garder la liste est assez coûteux :/
Si on décide de garder la liste on peut éviter de recalculer pro et contra à chaque fois et que l'updater lorsque quelqu'un vote up et vote down et garder la valeur dans la table comme ça on doit pas le recalculer à chaque fois que quelqu'un veut connaitre la confidence.
T'en penses quoi ?

**Comment by pverbist95** [comment]
On peut effectivement supprimer le champs Confidence, pour l'instant on ne l'utilise quand même pas, et comme tu dis il se recalcule très facilement.
> Garde-t-on la liste de tous les gens qui ont voté ? Sinon comment on sait si un mec a déjà voté pour l'empêcher de revoter ?

Oui pour l'instant ça me semble indispensable... ça va couter très cher à la db, mais je pense pas qu'on a le choix :/ Et je garderais les champs pro et contra, afin de limiter la casse et de pas toujours devoir la recalculer (comme tu le suggères)

Maintenant que j'y pense, j'ai fait une petite erreur: pro et contra ne devraient pas se trouver dans "Meaning", mais plutôt dans "Links". En effet, un utilisateur ne vote pas pour un meaning à proprement parlé, mais plutôt pour l'appartenance d'un mot à un meaning (nuance! :p). 
En ccl, on aurait:
- Meaning: avec les champs "id", "created_at" et "updated_at"
- Word: avec les champs "id", "created_at", "updated_at", "content", "language_id"
- Link: avec les champs "id", "created_at", "updated_at", "word_id", "meaning_id", **"pro", "contra"**
- une nouvelle classe (qu'on pourrait appeler "LinkVote", à discuter) avec "id", "created_at", "updated_at", **"link_id", "user_id" et "pro?"**
Est ce que ça ferait notre affaire? (Du moins, dans un premier temps?)

> Pour le moment tu gardes la liste ou pas ?

Pour l'instant je fais rien du tout :p Je me suis pas encore penché sur cette question, sauf ci-dessus.

> Pour ce qui est de la valeur de départ, je voyais plus (0, 0, 0.5) mais c'est discutable :)

Haha oui c'set vrai que (1, 9, 0.5) peut paraître bizarre, mais c'est pour éviter qu'un meaning soit approuvé trop rapidement.
Si on prend (0, 0, 0.5), il est possible que le meaning soit approuvé si un seul utilisateur le valide, et se retrouver dans la situation (1,0,1.0)
En initialisant "Contra" à 9, on impose qu'il y ait au moins 9 personnes qui vérifient le mot avant d'avoir une fiabilité de 50%, et il faut qu'il y ait environ 90 validations pour que la fiabilité passe à 90 %. Ceci permet de se prémunir contre les abus, même si c'est un peu fort (on pourrait initialiser contra à 5, ce serait déjà pas mal du tout). Bien évidemment, c'est encore à discuter :)

Bref, what do you think?

**Comment by blegat** [comment]
> Maintenant que j'y pense, j'ai fait une petite erreur: pro et contra ne devraient pas se trouver dans "Meaning", mais plutôt dans "Links". En effet, un utilisateur ne vote pas pour un meaning à proprement parlé, mais plutôt pour l'appartenance d'un mot à un meaning (nuance! :p). 
En ccl, on aurait:
- Meaning: avec les champs "id", "created_at" et "updated_at"
- Word: avec les champs "id", "created_at", "updated_at", "content", "language_id"
- Link: avec les champs "id", "created_at", "updated_at", "word_id", "meaning_id", **"pro", "contra"**
- une nouvelle classe (qu'on pourrait appeler "LinkVote", à discuter) avec "id", "created_at", "updated_at", **"link_id", "user_id" et "pro?"**
Est ce que ça ferait notre affaire? (Du moins, dans un premier temps?)

Oui ça m'a l'air bien :)
Deux questions subsistes:
- Ne ferais-t-on pas aussi un système de confiance pour un mot ? Ou alors on considère que l'existence d'un mot en tant que telle ne veut pas dire grand chose (au final juste un string). On peut par exemple imaginer que tous les strings existent (même si en pratique ils ne sont pas tous instanciés dans la db) et que le seul acte discutable est de lier ce string à un meaning. Donc je dirais aussi pas de pro/contra pour un mot comme tu as fait. C'est compréhensible ce que j'ai dit ? :-P
* Il faut gérer le fait que la confiance en un utilisateur évolue. Quand tu mets *"pro?"*, tu suggères qu'on "freeze" la confiance en cet utilisateur lors du vote et que si sa confiance évolue on update pas le nombre de points pour ce vote ? Il y a 3 possibitités:
1) Tous le monde a une influence de 1.
2) Un freeze (mais alors il peut retirer son vote et revoter et ça vaudra plus si il a gagné en confiance entre temps!)
3) On ne freeze pas et à chaque fois qu'on recalcule la confidence d'un link, le nombre de vote qu'un utilisateur a apporté peut changer. Le problème avec ça c'est qui si personne ne vote up ou down, on ne recalcule pas et donc ça pourrait ne pas changer pendant longtemps alors que la confiance des users a changé. Ou alors quand un user passe d'un niveau de confiance à un autre on recalcule la confidence de tous les links pour lesquels il a vote up. Ou alors on recalcule chaque jour ? Ou tant pis on s'en fout ? :-P
Quel option préfères-tu ? Sur stackexchange, on utilisent la 1) il me semble :)

> Haha oui c'set vrai que (1, 9, 0.5) peut paraître bizarre, mais c'est pour éviter qu'un meaning soit approuvé trop rapidement.
Si on prend (0, 0, 0.5), il est possible que le meaning soit approuvé si un seul utilisateur le valide, et se retrouver dans la situation (1,0,1.0)
En initialisant "Contra" à 9, on impose qu'il y ait au moins 9 personnes qui vérifient le mot avant d'avoir une fiabilité de 50%, et il faut qu'il y ait environ 90 validations pour que la fiabilité passe à 90 %. Ceci permet de se prémunir contre les abus, même si c'est un peu fort (on pourrait initialiser contra à 5, ce serait déjà pas mal du tout). Bien évidemment, c'est encore à discuter :)

> Bref, what do you think?

Je n'y avais pas pensé comme ça, pour moi un link était activé immédiatement.
Le nombre de vote a uniquement deux influences
1) Un vote élevé fait gagner de la confiance au créateur du link. Là il faut voir ce qu'on regarde, en effet on ne peut pas juste regarder le pourcentage de positifs car après un vote on peut être à 100%. On peut soit regarder le pourcentage de positifs à partir d'un certain nombre de votes, soit simplement regarder le nombre de votes positifs moins le nombre de votes négatifs (c'est ce que fait stackexchange).
2) À partir de soit un % trop petit (avec un minimum de votes), soit une différences (positifs moins négatifs) assez faible, un utilisateurs avec suffisament de confiance (la confiance nécessaire dépend du pourcentage/différence), l'utilisateur peut spprimer le link.

**Comment by pverbist95** [comment]
> Donc je dirais aussi pas de pro/contra pour un mot comme tu as fait

Oui, j'aurais tendance à faire comme ça, sinon la db va vraiment nous haïr :p 

> Il faut gérer le fait que la confiance en un utilisateur évolue.

Alors oui c'est très important. Perso, je penche pour la solution 1. Est-ce qu'on ferais aussi un système de messages, pour pouvoir commenter un link? Ce ne sera pas énormément utilisé, mais ça permet de faire remarquer des fautes de frappe (Binjour au lieu de Bonjour, etc)

> Pourcentage vs différences, activé immédiatement vs pas activé immédiatement.

Ton idée de regarder le pourcentage de positifs à partir d'un certain nombre de votes me plait pas mal... c'est donc un mixe des deux :) On pourrait dire que pour considérer un link comme étant valide, il faut 90% d'approbation avec un minimum de 40 votes. Qu'en penses-tu? Et pour invalider un link, on ferai comment? Moins de 20% d'approbation? Et si on se trouve entre 20 et 90%, on fait quoi? On attend d'avoir plus de votes et qu'un des deux extrêmes prenne le dessus?

Par contre, pour moi, un link est "activé" d'office, en ce sens qu'il ne faut pas attendre de validation extérieure avant de pouvoir s'entrainer dessus. N'importe qui peut faire sa liste tranquille et la partager.
Mais attention: s'il met n'importe quoi, il perdra bcp de points...
Ha oui, un truc amusant à faire serait de mettre, lorsqu'on affiche une liste, la confiance du link (c'est la raison pour laquelle j'avais laissé le champs "confidence", même si on peut le calculer facilement à partir de "pro" et de "contra"). L'utilisateur peut alors voir les link qui sont déjà validés et ceux qui sont (éventuellement) faux. Mais ça peut attendre une version ultérieure :)

Pour en revenir à notre utilisateur qui crée une liste, pour chaque nouveau link qu'il va introduire, il y a plusieurs possibilités:
- le link proposé est correct et n'a pas encore été créé dans la db. Dans ce cas, c'est comme s'il proposait un nouveau link. A partir d'un moment, le link sera approuvé et il gagnera des points
- le link proposé est correct et a déjà été créé dans la db. Dans ce cas, je sais pas quoi faire... est-ce qu'on considère que l'utilisateur vote +1 pour le link?
- le link proposé est incorrect et n'est pas dans la db: un nouveau link est proposé, mais au bout d'un moment les votes seront négatifs et il perdra des points
- le link proposé est incorrect et a déjà été proposé: même chose: on considère que c'est +1 ? :$

Avec les points gagnés, on pourrait faire un système de privilège comme dans stackexchange. Les privilèges à débloquer pourraient être:
- laisser un commentaire
- créer des listes publiques
- ...

(enfin, je sais pas si ce sera vraiment utile...)

**Comment by blegat** [comment]
> Est-ce qu'on ferais aussi un système de messages, pour pouvoir commenter un link? Ce ne sera pas énormément utilisé, mais ça permet de faire remarquer des fautes de frappe (Binjour au lieu de Bonjour, etc)

Très bonne remarque.
Je pense que ça n'a pas vraiment de sens de vote down sans expliquer pourquoi.
On pourrait obligé pour les vote down de
* soit créer une nouvelle raison de pourquoi le mot est faux
* soit choisir une raison déjà donnée.
On aura donc non-seulement un link avec beaucoup de vote down mais on verra aussi quelle est la raison la plus probable que c'est mauvais.
On peut aussi donner la possibilité de commenter sur les raisons (mais ajouter le vote up/down sur les commentaires ou le vote down sur les raisons je pense que c'est too much, tu en penses quoi ?)


Si je comprends bien valider/invalider, c'était juste pour savoir quand on fait un +1 ou -1 en confiance pour le user c'est ça ?

> Dans ce cas, je sais pas quoi faire... est-ce qu'on considère que l'utilisateur vote +1 pour le link?

On peut faire ça oui, éventuellement on peut faire une checkbox dans les préférences de l'utilisateur ou avant l'importation d'une liste.

> le link proposé est incorrect et a déjà été proposé: même chose: on considère que c'est +1 ? :$

Là par contre il faudrait plutôt générer un warning pour le prévenir et demander à l'utilisateur ce qu'il veut faire.

> Avec les points gagnés, on pourrait faire un système de privilège comme dans stackexchange. Les privilèges à débloquer pourraient être:
* laisser un commentaire
* créer des listes publiques

* Je pense pas que créer des listes publiques recquière un privilège. En soit tu crées ta liste, tu la rends publique mais personne ne la voit s'il ne va pas sur ton profil.
* Laisser un commentaire, ça dépend du commentaire, une raison/vote down sur un link doit demander du privilège alors qu'un commentaire sur une raison, tout le monde peut le faire.
* Aussi, plus on est privilégié, plus vite on peut supprimer un link. Maintenant, est-ce vraiment utile de supprimer un link ? Ça fait de la place dans la db mais on pourrait juste le cacher du site et si quelqu'un veut le rerajouter, on se rappelle que c'est faut. Sur le site on peut faire semblant qu'il est supprimé même si on s'en souvient dans la db. Maintenant je sais pas si c'est une bonne idée, je rappelle que removing a link est l'issue #1 :-P
